apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: aws-parameter-store
spec:
  provider:
    aws:
      service: ParameterStore
      region: eu-west-1
      role: arn:aws:iam::207916078383:role/external-secrets-ssm-parameter-store # the workload-account role ARN
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets-ssm
            namespace: external-secrets
            audiences:
              - sts.amazonaws.com
