apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-ssm
  namespace: external-secrets
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::207916078383:role/external-secrets-ssm-parameter-store
