apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: test-parameter
  namespace: external-secrets
spec:
  secretStoreRef:
    name: aws-parameter-store
    kind: ClusterSecretStore # ← see trap 1
  target:
    name: test-parameter # the Secret ESO will create
  data:
    - secretKey: test-parameter # the key inside that Secret (your choice)
      remoteRef:
        key: /homelab/test-parameter # ← see trap 2
