---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: aws-route53-credentials
  namespace: cert-manager
spec:
  encryptedData:
    secret-access-key: AgApO25voox+Uw9sTY7OIBO7NOcNzN/zJKjdidaEYhhB2MnDomPLJ/vXBnWmpf8t0HgZR9301ElAusH8xwDWvMAtI8yUzjVBgresObI/R+S6o2FEUhKt2X2MZo3TFrpeSPgNtFFkhINRiN52q+5c9Y45tO2aX5F6oRL7MX/cfRSZtHK7Ny1fBxErGcBvlfaxAaIeEnFrIWILf4OGPL7JVP3Cr+BNHFHI0UQEQJFyRoWnY0J7B6AXOLy4iIaOoxOgricKnCF14pxTpqWl1RFwx44bBPgSNmakC9mJ+n3c7fiSAjW61ZB1ozVgpsfk/r/8xtSUtT7X3u0kOAOzu6Ha5y0SXJAjeJATZLlkc1aoe/tEeqQWKga4ZiZb9xRQFf4G8isLQmjV2P1ouCIMhNHQTDbVIpP8ZShYp3qRCvbd5b6NbzPhTf7wkwSx3PNjDxpkEaZwwEbmHxzGAfGWtBRd2Ys5j1ZnhHlyXmN/oxN9ENlToYyD3GMP9LfW5qDBvjCuFsbO8BO401NrnrzqiJ0AydgdOQctIjkopgT7B0hyqvcX49Fd6Aj4i9y8EgSNqzVgKjOv5VaMELRg7rN2HCIQLY6SPAKVSBjL+037I+0qmbRVBQd7O6so7oX7QikB1FozajF9WM1MMBJIZZYv2UVmUl1dGjRGIS8W5RtUn3Q4yPXQQDHv0j3SL1gEFNvvbgHXZVSMkyVGad6j2Z0BdKxEk0lkaA1yTivQn3WVL8tsIaoKd32bNZ5rqw4U
  template:
    metadata:
      name: aws-route53-credentials
      namespace: cert-manager
    type: Opaque
