apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-ingress
  annotations:
    # On précise à Kubernetes que c'est Traefik qui gère cette règle
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hello-svc # Le nom exact de ton Service dans service.yaml
                port:
                  number: 80
