apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hello-world

resources:
  - namespace.yml
  - deployment.yml
  - service.yml
  - ingress.yml
  - configmap.yml

commonLabels:
  app: hello-world
