---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: basic-auth-secret
  namespace: hello-world
spec:
  encryptedData:
    users: AgB+Kox+VPWKQqo9wjatEPnSugasK7FQ2agKYO684N0OTALue06eX/EpAaR6sgid5ym/S1kJYQCGcOAzxx08TLz3Vr5Kr6pwdakLnzwg79u/QF8vcWATyOh6YkNMBeVPksS8BKyYDpHSdBea8uE+HfZKJezIW5M71N24VFtbUV98eHgX0YyHGLUIPiF2pA47kzmdZta8mozaibhWb6OCr/Gv4IBroGNaWkbkvFrOtbCp0fb9+7r9bvl0FY/dEuzLh3m69vacxAH6dN5NXbIrgZyImDVRrQAJCtmc9G+6wwHpPu2M5Uqmm5tHk/hNdy87Jc1iXX7GdHsFmISxaEU8wm+NhjAuXzaqqINicUEMo6zGUecqNLb0Qp/GERBu5hgohJFhfwo/s3KY9NGiJKbo/gOFFvrWtI4oah7UbbKsowa2dj0ZFvMSlCSRRQdBnx+6gaRm3EiJeSBbk+skGJasVAs2j3fIJvXK/o5BBIhAxIdTLYRuH+swEKW1cC2YTbGKYezeYdYnxp5mho4+HVPeP7v6irzmU0H/o2iohsA6FouBmpIPxiNFDvn2dwGs19/gpUvDUFj9DluflT5iTIBJd4u+sTBUItntYkUjIDo6SMKRRCJ5c/8RpwEYSHOkPuVckOjQLfhSeatz52YVjUIlwLnBg59nz2shJPi+jdftpkcgoNTltAE55TNllvDkxUdg9EYs/H5OvLKBhS0/+19nNrmZ4aDwgcIAcTK1
  template:
    metadata:
      name: basic-auth-secret
      namespace: hello-world
    type: Opaque
