---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: basic-auth-secret
  namespace: hello-world
spec:
  encryptedData:
    users: AgAUASZZCCpSnUwJPnl+OIT7t07bQ1pX/nuJeP/prBjlxyRwcIacMrpg1i0ozqZp/0GW4sE0tRTSyo/BbScRFOOho9edEIqnNAJ88LxPgB+CoB+32Bl++ULRU4CVpOXElYBvovBjIXpdvGfv/lG8x+iey+O3CPwQRwCvfn+Zv49Cl+vfMjNAOfspXqHT+CbG7YIwL1o0O/KPoG6Xx1/U0QxGp9d3jwqQ/o0nPFUNqLIpPgDfhjguLFp65qEvYwbtZayN36MEr1augQQ12MG3vrw094uXvoYQouS/v2BNMvLITEVEfDelR78jXIVvVOfuDfky6N5KpKKcu0vCXDMCfKmkKHtroD44GO8NIJuJhBOiKUi0XIx9D/GRYeIRorkLIn++rECHUWb8Zm/y8dEzko722CW1BK4kk8QfED7pOUP6j0l3x7HLL81lP5TeA7qKiF1M4O4JSLj+8wwhVSIg2D/tVcD/t1P+ikG11357dBDz5fEEcJE7oXhn+Y/iNTvMHdFo2POiqDd86zEjqTjqTEOGMZuhJrOQ0sNdrsuWluUN43OySqrfJ2toXs4zz5+T030kbaH5TUI8+y0aVRfqxuIr6/JsCu3nyrTqKMMcD7OlZyMA0G3ENAe4n4Cd+dC25DRQmCJHDWvjdruDbk+oS/V7QTqP5Pzy8Qw3fz2bLniqnIJ/Qp7cVNpWYLa1tP5/H/i9AChAzStVPd8qjKDx5z7Ry5dDXnOH3ebq+L9Z3SMZLq5Utcco3tZT0Nk=
  template:
    metadata:
      name: basic-auth-secret
      namespace: hello-world
    type: Opaque
