apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yml
  # - dashboard-ingress.yml

helmCharts:
  - name: traefik
    releaseName: traefik
    version: 39.0.2 # On reste sur la 33 ou 39, mais avec les bonnes valeurs
    repo: https://traefik.github.io/charts
    namespace: traefik
    valuesInline:
      # On retire installCRDs d'ici car le chart ne le reconnaît pas à cet endroit
      api:
        enabled: true # Attention: c'est souvent 'enabled' maintenant
        dashboard: true
        insecure: true
      deployment:
        kind: Deployment
      service:
        type: ClusterIP
      ports:
        web:
          hostPort: 80
        websecure:
          hostPort: 443
      ingressClass:
        enabled: true
        isDefaultClass: true
