apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yml
  # Laisse ton Ingress commenté pour l'instant, on va vérifier le port-forward d'abord
  # - dashboard-ingress.yml

helmCharts:
  - name: traefik
    releaseName: traefik
    version: 39.0.2
    repo: https://traefik.github.io/charts
    namespace: traefik
    includeCRDs: true # LA VRAIE CLÉ EST ICI (Niveau Kustomize)
    valuesInline: # Niveau Helm
      api:
        dashboard: true
        insecure: true
      deployment:
        kind: Deployment
      service:
        type: ClusterIP
      ports:
        web:
          hostPort: 80
        websecure:
          hostPort: 443
      ingressClass:
        enabled: true
        isDefaultClass: true
