---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: basic-auth-secret
  namespace: traefik
spec:
  encryptedData:
    users: AgB6G7ES9ScPDQx2Y47+aop0xvgsD42IJLmZXzlMWx+RRcNCcQBp0BIyQyc3zeOLXak+2h4yEzz/AwgWBYOgMceAzGjX9GOqw0k3HvUAJRoHeJ1k3KSaUrnOXg2N/2O1nj2G9BYlITgtDT1KoPwd6sSEfp1tuPJm1NdoUlWulgE+ucqVRR0l7q5PSN6ieyQXU26lRfXeGTFADZVGDZ9uHrUuqEd9IbVibA3+54YTr9t9JYYxtTqAphNkEVvTCLEGUGfIERnxDF+F1H9oICZHxgVdwSE7R1tR+1L0i2tSZuLcEljAugDzvRH96O0Wl84NFaYnjX4dE+vUb5Q2zvOMOaLulZP6LLUl5UoYCn9ACdnuDUiexSzdKceSlRnaqRhZXhMfeODsBXe+qONCxdikEofGrCV367i8m1W+tmIyM0XOAp7K4gXJJ7wFFi+2Dz88FUFmSZx8eaw3CuNxzeq2aFqpaCedzOITjYAtITQnrBeRQYsDckcObww5gzI5potdMzBhoI4L1/+j1voAtlQ5lkl5mAU/EctTMwKMj/oaiasSZBdY6F0ucFUsMWG9yTnvY208kcna9fafriivhjeO8H/H1XBjvkK9OJW28pWvy/N14QHqW/6eBCU0cnF4r6qHFgPSJc+9kqLGNk9wM8B8LM8ZfucmrONkvPuAdKFsxwVayeLfbAOjxTAAtnRRIx8W7c2s9xFafoGveHX3dzEofRy9JvySuYIf6f9L6aEk4IRPh5nx3vOiGh6Ctys=
  template:
    metadata:
      name: basic-auth-secret
      namespace: traefik
    type: Opaque
