apiVersion: v1
kind: ConfigMap
metadata:
  name: zurg-config
  namespace: media
data:
  config.yml: |
    zurg: v1
    host: "[::]"
    port: 9999
    # Le token est passé de manière sécurisée via la variable d'environnement ZURG_TOKEN

    # Configuration des dossiers virtuels (ce que verra Jellyfin)
    directories:
      torrents:
        group: 1
        group_order: 1
        filters:
          - regex: /.*/
