apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zurg-data
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi # Très largement suffisant pour du texte/métadonnées
