apiVersion: v1
kind: ConfigMap
metadata:
  name: rclone-config
  namespace: media
data:
  rclone.conf: |
    [zurg]
    type = webdav
    url = http://zurg:9999/dav
    vendor = other
    pacer_min_sleep = 0
