apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yml
  - networkpolicy.yml
  - ingress.yml

helmCharts:
  - name: podinfo
    releaseName: podinfo
    version: 6.15.0
    repo: https://stefanprodan.github.io/podinfo
    namespace: podinfo
    skipTests: true
